# Generated by Django 4.0.4 on 2022-12-14 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='paulo.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bid_time_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to=None)),
                ('highest_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('highest_bidder', models.CharField(default='', max_length=255)),
                ('owner_name', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owns', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='mainapp.qanda')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(to='mainapp.item'),
        ),
    ]
